// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/immutable/*",
    "/_app/version.json",
    "/availability/defaults.json",
    "/availability/timezones.json",
    "/cache-warming.json",
    "/favicon.png",
    "/favicon.svg",
    "/screenshot.png"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Library/Mines/Github/Cloud-Meet/.wrangler/tmp/pages-txRYVd/bundledWorker-0.22424779458887123.mjs";
import { isRoutingRuleMatch } from "/Library/Mines/Github/Cloud-Meet/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Library/Mines/Github/Cloud-Meet/.wrangler/tmp/pages-txRYVd/bundledWorker-0.22424779458887123.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=z07v2xv5eoi.js.map
